### ISSUE TITLE
Apparent naming conflict with OpenCV's ts module

### ISSUE THREAD

**Issue by tcies** [ethz-asl/eigen_checks#28]
I can't link eigen_checks with opencv_catkin:
```
/usr/bin/ld: /home/titus/catkin_ws/devel/lib/libopencv_ts.a(ts_gtest.cpp.o): relocation
R_X86_64_32S against `_ZTVN7testing8internal26ThreadLocalValueHolderBaseE' 
can not be used when making a shared object; recompile with -fPIC
```
Seems like there is an infortunate naming conflict between eigen_checks and OpenCV's `ts` module, in particular ts_gtest.cpp .

**Comment by simonlynen** [comment]
Assuming this is fixed by now since we link opencv in our proj.
